//
// FX Version: fx_5_0
//
// 1 local buffer(s)
//
cbuffer CBufferPerObject
{
    float4x4 WorldViewProjection : WORLDVIEWPROJECTION
    <
        String UIWidget = "None";
    >;                                  // Offset:    0, size:   64
}

//
// 3 local object(s)
//
TextureCube SkyboxTexture
<
    String UIName = "Skybox Texture";
    String ResourceType = "3D";
>;
SamplerState TrilinearSampler
{
    Filter   = uint(MIN_MAG_MIP_LINEAR /* 21 */);
};
RasterizerState DisableCulling
{
    CullMode = uint(NONE /* 1 */);
};

//
// 1 groups(s)
//
fxgroup
{
    //
    // 1 technique(s)
    //
    technique11 main11
    {
        pass p0
        {
            VertexShader = asm {
                //
                // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                //
                //
                // Buffer Definitions: 
                //
                // cbuffer CBufferPerObject
                // {
                //
                //   float4x4 WorldViewProjection;      // Offset:    0 Size:    64
                //
                // }
                //
                //
                // Resource Bindings:
                //
                // Name                                 Type  Format         Dim Slot Elements
                // ------------------------------ ---------- ------- ----------- ---- --------
                // CBufferPerObject                  cbuffer      NA          NA    0        1
                //
                //
                //
                // Input signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // POSITION                 0   xyzw        0     NONE   float   xyzw
                //
                //
                // Output signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // SV_Position              0   xyzw        0      POS   float   xyzw
                // TEXCOORD                 0   xyz         1     NONE   float   xyz 
                //
                vs_4_0
                dcl_constantbuffer cb0[4], immediateIndexed
                dcl_input v0.xyzw
                dcl_output_siv o0.xyzw, position
                dcl_output o1.xyz
                dp4 o0.x, v0.xyzw, cb0[0].xyzw
                dp4 o0.y, v0.xyzw, cb0[1].xyzw
                dp4 o0.z, v0.xyzw, cb0[2].xyzw
                dp4 o0.w, v0.xyzw, cb0[3].xyzw
                mov o1.xyz, v0.xyzx
                ret 
                // Approximately 6 instruction slots used
                            
            };
            GeometryShader = NULL;
            PixelShader = asm {
                //
                // Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
                //
                //
                // Resource Bindings:
                //
                // Name                                 Type  Format         Dim Slot Elements
                // ------------------------------ ---------- ------- ----------- ---- --------
                // TrilinearSampler                  sampler      NA          NA    0        1
                // SkyboxTexture                     texture  float4        cube    0        1
                //
                //
                //
                // Input signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // SV_Position              0   xyzw        0      POS   float       
                // TEXCOORD                 0   xyz         1     NONE   float   xyz 
                //
                //
                // Output signature:
                //
                // Name                 Index   Mask Register SysValue  Format   Used
                // -------------------- ----- ------ -------- -------- ------- ------
                // SV_Target                0   xyzw        0   TARGET   float   xyzw
                //
                ps_4_0
                dcl_sampler s0, mode_default
                dcl_resource_texturecube (float,float,float,float) t0
                dcl_input_ps linear v1.xyz
                dcl_output o0.xyzw
                sample o0.xyzw, v1.xyzx, t0.xyzw, s0
                ret 
                // Approximately 2 instruction slots used
                            
            };
            RasterizerState = DisableCulling;
        }

    }

}

